version: "3.8"

services:
  postgres:
    image: postgres:17.0-alpine3.19
    container_name: samapos-postgres
    restart: always
    environment:
      POSTGRES_DB: samapos
      POSTGRES_USER: pius
      POSTGRES_PASSWORD: piuspius
    ports:
      - "5432:5432"
    volumes:
      - samapos_data:/var/lib/postgresql/data
    networks:
      - backend_network

volumes:
  samapos_data:
    driver: local

networks:
  backend_network:
    driver: bridge
