version: "3.8"

services:
  postgres:
    image: postgres:17.0-alpine3.19
    container_name: stackseek-postgres
    restart: always
    environment:
      POSTGRES_DB: stackseek
      POSTGRES_USER: seeky
      POSTGRES_PASSWORD: seeky123
    ports:
      - "5432:5432"
    volumes:
      - stackseek_data:/var/lib/postgresql/data
    networks:
      - backend_network

volumes:
  stackseek_data:
    driver: local

networks:
  backend_network:
    driver: bridge
